interface CreatorProfile {
  id: string;
  name: string;
  platform: "instagram" | "tiktok" | "youtube";
  country: string;
  followers: number;
  engagementRate: number;
  category: string;
}

// input

const input: CreatorProfile[] = [
  {
    id: "c1",
    name: "Emma Johnson",
    platform: "instagram",
    country: "US",
    followers: 34000,
    engagementRate: 3.2,
    category: "movies",
  },
  {
    id: "c2",
    name: "Michael Chen",
    platform: "tiktok",
    country: "US",
    followers: 125000,
    engagementRate: 8.5,
    category: "comedy",
  },
  {
    id: "c3",
    name: "Oliver Smith",
    platform: "youtube",
    country: "UK",
    followers: 890000,
    engagementRate: 4.1,
    category: "gaming",
  },
  {
    id: "c4",
    name: "Sophia Mueller",
    platform: "instagram",
    country: "DE",
    followers: 56000,
    engagementRate: 2.8,
    category: "fashion",
  },
  {
    id: "c5",
    name: "Lucas Dubois",
    platform: "tiktok",
    country: "FR",
    followers: 230000,
    engagementRate: 12.3,
    category: "dance",
  },
  {
    id: "c6",
    name: "Ava Williams",
    platform: "youtube",
    country: "US",
    followers: 2100000,
    engagementRate: 6.7,
    category: "tech",
  },
  {
    id: "c7",
    name: "Noah Tremblay",
    platform: "instagram",
    country: "CA",
    followers: 78000,
    engagementRate: 4.5,
    category: "food",
  },
  {
    id: "c8",
    name: "Isla Thompson",
    platform: "tiktok",
    country: "AU",
    followers: 450000,
    engagementRate: 9.2,
    category: "comedy",
  },
  {
    id: "c9",
    name: "Haruto Tanaka",
    platform: "youtube",
    country: "JP",
    followers: 3400000,
    engagementRate: 5.8,
    category: "anime",
  },
  {
    id: "c10",
    name: "Valentina Silva",
    platform: "instagram",
    country: "BR",
    followers: 120000,
    engagementRate: 3.9,
    category: "fitness",
  },
  {
    id: "c11",
    name: "Mateo Rodriguez",
    platform: "tiktok",
    country: "MX",
    followers: 670000,
    engagementRate: 11.4,
    category: "music",
  },
  {
    id: "c12",
    name: "Priya Sharma",
    platform: "youtube",
    country: "IN",
    followers: 5600000,
    engagementRate: 7.3,
    category: "education",
  },
  {
    id: "c13",
    name: "Marco Rossi",
    platform: "instagram",
    country: "IT",
    followers: 45000,
    engagementRate: 2.1,
    category: "travel",
  },
  {
    id: "c14",
    name: "Carmen Garcia",
    platform: "tiktok",
    country: "ES",
    followers: 890000,
    engagementRate: 14.2,
    category: "fashion",
  },
  {
    id: "c15",
    name: "Ji-yoon Park",
    platform: "youtube",
    country: "KR",
    followers: 1200000,
    engagementRate: 8.9,
    category: "beauty",
  },
  {
    id: "c16",
    name: "Daan Bakker",
    platform: "instagram",
    country: "NL",
    followers: 34000,
    engagementRate: 5.6,
    category: "photography",
  },
  {
    id: "c17",
    name: "Elsa Lindqvist",
    platform: "tiktok",
    country: "SE",
    followers: 230000,
    engagementRate: 10.1,
    category: "fitness",
  },
  {
    id: "c18",
    name: "Lars Olsen",
    platform: "youtube",
    country: "NO",
    followers: 450000,
    engagementRate: 4.3,
    category: "vlog",
  },
  {
    id: "c19",
    name: "Freja Nielsen",
    platform: "instagram",
    country: "DK",
    followers: 67000,
    engagementRate: 3.8,
    category: "lifestyle",
  },
  {
    id: "c20",
    name: "Aino Virtanen",
    platform: "tiktok",
    country: "FI",
    followers: 340000,
    engagementRate: 13.7,
    category: "cooking",
  },
  {
    id: "c21",
    name: "Jakub Kowalski",
    platform: "youtube",
    country: "PL",
    followers: 890000,
    engagementRate: 6.2,
    category: "gaming",
  },
  {
    id: "c22",
    name: "Anastasia Volkov",
    platform: "instagram",
    country: "RU",
    followers: 56000,
    engagementRate: 2.4,
    category: "art",
  },
  {
    id: "c23",
    name: "Mehmet Yilmaz",
    platform: "tiktok",
    country: "TR",
    followers: 1200000,
    engagementRate: 15.8,
    category: "comedy",
  },
  {
    id: "c24",
    name: "Thabo Ndlovu",
    platform: "youtube",
    country: "ZA",
    followers: 340000,
    engagementRate: 5.1,
    category: "music",
  },
  {
    id: "c25",
    name: "Fatima Hassan",
    platform: "instagram",
    country: "EG",
    followers: 23000,
    engagementRate: 4.7,
    category: "fashion",
  },
  {
    id: "c26",
    name: "Chinedu Okafor",
    platform: "tiktok",
    country: "NG",
    followers: 670000,
    engagementRate: 11.9,
    category: "dance",
  },
  {
    id: "c27",
    name: "Wanjiru Mwangi",
    platform: "youtube",
    country: "KE",
    followers: 120000,
    engagementRate: 3.5,
    category: "education",
  },
  {
    id: "c28",
    name: "Kwame Addo",
    platform: "instagram",
    country: "GH",
    followers: 45000,
    engagementRate: 6.8,
    category: "food",
  },
  {
    id: "c29",
    name: "Somchai Srisai",
    platform: "tiktok",
    country: "TH",
    followers: 890000,
    engagementRate: 9.4,
    category: "beauty",
  },
  {
    id: "c30",
    name: "Minh Nguyen",
    platform: "youtube",
    country: "VN",
    followers: 2300000,
    engagementRate: 7.6,
    category: "tech",
  },
  {
    id: "c31",
    name: "Maria Santos",
    platform: "instagram",
    country: "PH",
    followers: 78000,
    engagementRate: 4.2,
    category: "travel",
  },
  {
    id: "c32",
    name: "Budi Wijaya",
    platform: "tiktok",
    country: "ID",
    followers: 340000,
    engagementRate: 12.8,
    category: "comedy",
  },
  {
    id: "c33",
    name: "Wei Ling Tan",
    platform: "youtube",
    country: "MY",
    followers: 560000,
    engagementRate: 5.9,
    category: "gaming",
  },
  {
    id: "c34",
    name: "Jun Jie Lim",
    platform: "instagram",
    country: "SG",
    followers: 120000,
    engagementRate: 3.1,
    category: "fitness",
  },
  {
    id: "c35",
    name: "Ka Ming Wong",
    platform: "tiktok",
    country: "HK",
    followers: 450000,
    engagementRate: 10.5,
    category: "music",
  },
  {
    id: "c36",
    name: "Ting Wei Chen",
    platform: "youtube",
    country: "TW",
    followers: 890000,
    engagementRate: 6.4,
    category: "anime",
  },
  {
    id: "c37",
    name: "Yuki Zhang",
    platform: "instagram",
    country: "CN",
    followers: 2300000,
    engagementRate: 8.7,
    category: "fashion",
  },
  {
    id: "c38",
    name: "Santiago Lopez",
    platform: "tiktok",
    country: "AR",
    followers: 67000,
    engagementRate: 14.6,
    category: "dance",
  },
  {
    id: "c39",
    name: "Valentina Contreras",
    platform: "youtube",
    country: "CL",
    followers: 340000,
    engagementRate: 4.8,
    category: "vlog",
  },
  {
    id: "c40",
    name: "Camila Gomez",
    platform: "instagram",
    country: "CO",
    followers: 56000,
    engagementRate: 3.3,
    category: "lifestyle",
  },
  {
    id: "c41",
    name: "Diego Flores",
    platform: "tiktok",
    country: "PE",
    followers: 120000,
    engagementRate: 11.2,
    category: "cooking",
  },
  {
    id: "c42",
    name: "Andrea Martinez",
    platform: "youtube",
    country: "VE",
    followers: 89000,
    engagementRate: 5.5,
    category: "music",
  },
  {
    id: "c43",
    name: "Luciana Ferreira",
    platform: "instagram",
    country: "UY",
    followers: 34000,
    engagementRate: 2.9,
    category: "art",
  },
  {
    id: "c44",
    name: "Gabriel Acosta",
    platform: "tiktok",
    country: "PY",
    followers: 230000,
    engagementRate: 13.3,
    category: "comedy",
  },
  {
    id: "c45",
    name: "Fernando Rojas",
    platform: "youtube",
    country: "BO",
    followers: 67000,
    engagementRate: 6.1,
    category: "education",
  },
  {
    id: "c46",
    name: "Daniela Vega",
    platform: "instagram",
    country: "EC",
    followers: 45000,
    engagementRate: 4.4,
    category: "food",
  },
  {
    id: "c47",
    name: "Sebastian Morales",
    platform: "tiktok",
    country: "CR",
    followers: 89000,
    engagementRate: 9.8,
    category: "beauty",
  },
  {
    id: "c48",
    name: "Isabella Castillo",
    platform: "youtube",
    country: "PA",
    followers: 120000,
    engagementRate: 7.2,
    category: "tech",
  },
  {
    id: "c49",
    name: "Alejandro Reyes",
    platform: "instagram",
    country: "GT",
    followers: 78000,
    engagementRate: 3.6,
    category: "travel",
  },
  {
    id: "c50",
    name: "Maria Fernanda Cruz",
    platform: "tiktok",
    country: "HN",
    followers: 56000,
    engagementRate: 12.1,
    category: "fashion",
  },
  {
    id: "c51",
    name: "Javier Mendoza",
    platform: "youtube",
    country: "SV",
    followers: 34000,
    engagementRate: 5.3,
    category: "gaming",
  },
  {
    id: "c52",
    name: "Ana Lucia Torres",
    platform: "instagram",
    country: "NI",
    followers: 23000,
    engagementRate: 2.6,
    category: "fitness",
  },
  {
    id: "c53",
    name: "Carlos Jimenez",
    platform: "tiktok",
    country: "DO",
    followers: 67000,
    engagementRate: 10.9,
    category: "music",
  },
  {
    id: "c54",
    name: "Yamila Perez",
    platform: "youtube",
    country: "CU",
    followers: 45000,
    engagementRate: 4.9,
    category: "dance",
  },
  {
    id: "c55",
    name: "Sofia Ramirez",
    platform: "instagram",
    country: "PR",
    followers: 89000,
    engagementRate: 3.7,
    category: "lifestyle",
  },
  {
    id: "c56",
    name: "Marcus Bennett",
    platform: "tiktok",
    country: "JM",
    followers: 120000,
    engagementRate: 15.2,
    category: "cooking",
  },
  {
    id: "c57",
    name: "Keisha Williams",
    platform: "youtube",
    country: "TT",
    followers: 34000,
    engagementRate: 6.6,
    category: "vlog",
  },
  {
    id: "c58",
    name: "Tasha Clarke",
    platform: "instagram",
    country: "BB",
    followers: 23000,
    engagementRate: 4.1,
    category: "photography",
  },
  {
    id: "c59",
    name: "Brandon Johnson",
    platform: "tiktok",
    country: "BS",
    followers: 56000,
    engagementRate: 11.7,
    category: "comedy",
  },
  {
    id: "c60",
    name: "Jasmine Flowers",
    platform: "youtube",
    country: "BZ",
    followers: 78000,
    engagementRate: 5.4,
    category: "music",
  },
  {
    id: "c61",
    name: "Rajesh Kumar",
    platform: "instagram",
    country: "SR",
    followers: 45000,
    engagementRate: 2.8,
    category: "art",
  },
  {
    id: "c62",
    name: "Nia Thompson",
    platform: "tiktok",
    country: "GY",
    followers: 67000,
    engagementRate: 13.9,
    category: "fashion",
  },
  {
    id: "c63",
    name: "Antoine Laurent",
    platform: "youtube",
    country: "GF",
    followers: 120000,
    engagementRate: 7.8,
    category: "gaming",
  },
  {
    id: "c64",
    name: "Claire Fontaine",
    platform: "instagram",
    country: "MQ",
    followers: 34000,
    engagementRate: 4.5,
    category: "food",
  },
  {
    id: "c65",
    name: "Julie Moreau",
    platform: "tiktok",
    country: "GP",
    followers: 89000,
    engagementRate: 9.6,
    category: "beauty",
  },
  {
    id: "c66",
    name: "Thomas Bernard",
    platform: "youtube",
    country: "RE",
    followers: 230000,
    engagementRate: 6.3,
    category: "tech",
  },
  {
    id: "c67",
    name: "Maelle Durand",
    platform: "instagram",
    country: "YT",
    followers: 56000,
    engagementRate: 3.4,
    category: "travel",
  },
  {
    id: "c68",
    name: "Nicolas Mercier",
    platform: "tiktok",
    country: "NC",
    followers: 78000,
    engagementRate: 12.4,
    category: "fitness",
  },
  {
    id: "c69",
    name: "Teiva Manutahi",
    platform: "youtube",
    country: "PF",
    followers: 45000,
    engagementRate: 5.7,
    category: "music",
  },
  {
    id: "c70",
    name: "Sosefina Tui",
    platform: "instagram",
    country: "WF",
    followers: 23000,
    engagementRate: 2.2,
    category: "dance",
  },
  {
    id: "c71",
    name: "Jean-Pierre Leblanc",
    platform: "tiktok",
    country: "PM",
    followers: 67000,
    engagementRate: 14.1,
    category: "lifestyle",
  },
  {
    id: "c72",
    name: "Marie Lefevre",
    platform: "youtube",
    country: "BL",
    followers: 34000,
    engagementRate: 6.9,
    category: "cooking",
  },
  {
    id: "c73",
    name: "Pierre Martin",
    platform: "instagram",
    country: "MF",
    followers: 89000,
    engagementRate: 4.6,
    category: "photography",
  },
  {
    id: "c74",
    name: "Sophie Dubois",
    platform: "tiktok",
    country: "SX",
    followers: 120000,
    engagementRate: 10.3,
    category: "comedy",
  },
  {
    id: "c75",
    name: "Jan van Dijk",
    platform: "youtube",
    country: "CW",
    followers: 56000,
    engagementRate: 7.1,
    category: "education",
  },
  {
    id: "c76",
    name: "Elena Ruiz",
    platform: "instagram",
    country: "AW",
    followers: 78000,
    engagementRate: 3.9,
    category: "food",
  },
  {
    id: "c77",
    name: "Maria van der Berg",
    platform: "tiktok",
    country: "CW",
    followers: 230000,
    engagementRate: 13.5,
    category: "beauty",
  },
  {
    id: "c78",
    name: "Pieter de Jong",
    platform: "youtube",
    country: "BQ",
    followers: 45000,
    engagementRate: 5.8,
    category: "gaming",
  },
  {
    id: "c79",
    name: "Akira Ono",
    platform: "instagram",
    country: "SS",
    followers: 67000,
    engagementRate: 4.3,
    category: "fitness",
  },
  {
    id: "c80",
    name: "Amina Yusuf",
    platform: "tiktok",
    country: "SO",
    followers: 89000,
    engagementRate: 11.8,
    category: "music",
  },
  {
    id: "c81",
    name: "Hassan Ali",
    platform: "youtube",
    country: "DJ",
    followers: 34000,
    engagementRate: 6.5,
    category: "vlog",
  },
  {
    id: "c82",
    name: "Samira Tesfaye",
    platform: "instagram",
    country: "ER",
    followers: 23000,
    engagementRate: 3.2,
    category: "fashion",
  },
  {
    id: "c83",
    name: "Dawit Bekele",
    platform: "tiktok",
    country: "ET",
    followers: 56000,
    engagementRate: 14.8,
    category: "dance",
  },
  {
    id: "c84",
    name: "Noura Ibrahim",
    platform: "youtube",
    country: "SD",
    followers: 78000,
    engagementRate: 5.1,
    category: "lifestyle",
  },
  {
    id: "c85",
    name: "Mahamat Idriss",
    platform: "instagram",
    country: "TD",
    followers: 45000,
    engagementRate: 4.7,
    category: "cooking",
  },
  {
    id: "c86",
    name: "Aicha Moussa",
    platform: "tiktok",
    country: "NE",
    followers: 67000,
    engagementRate: 12.6,
    category: "art",
  },
  {
    id: "c87",
    name: "Amadou Keita",
    platform: "youtube",
    country: "ML",
    followers: 120000,
    engagementRate: 7.4,
    category: "music",
  },
  {
    id: "c88",
    name: "Mariam Sanou",
    platform: "instagram",
    country: "BF",
    followers: 34000,
    engagementRate: 3.5,
    category: "comedy",
  },
  {
    id: "c89",
    name: "Binta Embalo",
    platform: "tiktok",
    country: "GW",
    followers: 89000,
    engagementRate: 10.7,
    category: "education",
  },
  {
    id: "c90",
    name: "Omar Jallow",
    platform: "youtube",
    country: "GM",
    followers: 230000,
    engagementRate: 6.8,
    category: "tech",
  },
  {
    id: "c91",
    name: "Aissatou Barry",
    platform: "instagram",
    country: "GN",
    followers: 56000,
    engagementRate: 4.9,
    category: "travel",
  },
  {
    id: "c92",
    name: "Kadiatu Kamara",
    platform: "tiktok",
    country: "SL",
    followers: 78000,
    engagementRate: 13.2,
    category: "fitness",
  },
  {
    id: "c93",
    name: "James Wilson",
    platform: "youtube",
    country: "LR",
    followers: 45000,
    engagementRate: 5.6,
    category: "photography",
  },
  {
    id: "c94",
    name: "Esther Kone",
    platform: "instagram",
    country: "CI",
    followers: 67000,
    engagementRate: 3.8,
    category: "food",
  },
  {
    id: "c95",
    name: "Kwesi Boateng",
    platform: "tiktok",
    country: "GH",
    followers: 120000,
    engagementRate: 9.1,
    category: "beauty",
  },
  {
    id: "c96",
    name: "Abena Mensah",
    platform: "youtube",
    country: "TG",
    followers: 34000,
    engagementRate: 7.3,
    category: "gaming",
  },
  {
    id: "c97",
    name: "Koffi Agbodji",
    platform: "instagram",
    country: "BJ",
    followers: 23000,
    engagementRate: 4.4,
    category: "lifestyle",
  },
  {
    id: "c98",
    name: "Awa Ndiaye",
    platform: "tiktok",
    country: "SN",
    followers: 89000,
    engagementRate: 11.3,
    category: "dance",
  },
  {
    id: "c99",
    name: "Moussa Diallo",
    platform: "youtube",
    country: "MR",
    followers: 56000,
    engagementRate: 6.2,
    category: "vlog",
  },
  {
    id: "c100",
    name: "Fanta Bamba",
    platform: "instagram",
    country: "GNB",
    followers: 78000,
    engagementRate: 5.9,
    category: "cooking",
  },
];

let output = input
  .filter((u: CreatorProfile): boolean => {
    return u.platform != "tiktok" && u.followers > 1000000;
  })
  .sort((a, b) => {
    return b.followers - a.followers;
  })
  .reduce((acc, item: CreatorProfile) => {
    const key = item.platform;
    if (!acc[key]) {
      acc[key] = [];
    }

    acc[key].push(
      Object.fromEntries(
        Object.entries(item).filter(
          ([key]) => ["platform", "id", "name"].indexOf(key) != -1,
        ),
      ),
    );

    return acc;
  }, {});
//.map((u) => u.name + ":" + u.followers);

console.log(output);

